services:
  pyfractal:
    build:
      context: .
      dockerfile: compress.dockerfile
    environment:
      - PROGRAM_NAME=main
      - DATA_DIR=/app/data
      - DATASET=ligand_PLP.txt
    volumes:
      - .:/app
    # command: bash run_metadata_with_different_datasets.sh
    command: python src/main.py
